# -*- coding: utf-8 -*-
"""convert tfjs to pb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/untszlung/373c64b9772092f4bdebd136be99bca2/convert-tfjs-to-pb.ipynb
"""

!pip install tensorflow==2.0.0

!pip install tensorflowjs

import tensorflowjs as tfjs

model = tfjs.converters.load_keras_model('./model.json')
model.save('./saved_model')

import tensorflow as tf
print("Converting .pb to .tflite ..........")

graph_def_file = './saved_model' 
input_arrays = ['input']
output_arrays = ['dense_Dense2']
output = 'model.tflite'
converter = tf.lite.TFLiteConverter.from_saved_model(graph_def_file)
tflite_model = converter.convert()

open(output, "wb").write(tflite_model)